rest:
    resource: "https://api.weatherxm.com/api/v1/auth/login"
    method: POST
    payload: '{"username": "example@wxm.com", "password": "verrystrongpassword"}'
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    sensor:
      - name: "wxm_token"
        value_template: '1'
        json_attributes:
          - token
          - refreshToken
